### ISSUE TITLE
Exception in Campaign Creation

### ISSUE THREAD

**Issue by NagarajVinayagam** [facebook/facebook-java-business-sdk#137]
Exception in thread "main" com.facebook.ads.sdk.APIException$FailedRequestException: {"error":{"message":"Invalid appsecret_proof provided in the API argument","type":"GraphMethodException","code":100,"fbtrace_id":"HzIrLRaH1RM"}}
	at com.facebook.ads.sdk.APIRequest.readResponse(APIRequest.java:226)
	at com.facebook.ads.sdk.APIRequest.access$100(APIRequest.java:47)
	at com.facebook.ads.sdk.APIRequest$DefaultRequestExecutor.sendPost(APIRequest.java:409)
	at com.facebook.ads.sdk.APIRequest$DefaultRequestExecutor.execute(APIRequest.java:335)
	at com.facebook.ads.sdk.APIRequest.executeInternal(APIRequest.java:160)
	at com.facebook.ads.sdk.AdAccount$APIRequestCreateCampaign.execute(AdAccount.java:7612)
	at com.facebook.ads.sdk.AdAccount$APIRequestCreateCampaign.execute(AdAccount.java:7607)
	at com.sciera.facebook.ad.QuickStartExample.main(QuickStartExample.java:21)
Caused by: java.io.IOException: Server returned HTTP response code: 400 for URL: https://graph.facebook.com/v2.11/act_323632118042888/campaigns
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection$6.run(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection$6.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
	at com.facebook.ads.sdk.APIRequest.readResponse(APIRequest.java:207)
	... 7 more
Caused by: java.io.IOException: Server returned HTTP response code: 400 for URL: https://graph.facebook.com/v2.11/act_323632118042888/campaigns
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.net.HttpURLConnection.getResponseCode(Unknown Source)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(Unknown Source)
	at com.facebook.ads.sdk.APIRequest.readResponse(APIRequest.java:205)
	... 7 more

**Comment by ellentao** [comment]
Hey, thanks for your comment! This is actually an api issue. Please report the issue on Devsite Bug Report channel: https://developers.facebook.com/support/bugs/ Thanks!
