### ISSUE TITLE
NPE in APIRequest

### ISSUE THREAD

**Issue by jaimeferreira** [facebook/facebook-java-business-sdk#139]
When an API request fails, the exception handling throws an NPE. It's assuming that there is an error stream but it can be null.
```java
java.lang.NullPointerException: null
  at java.io.Reader.<init>(Reader.java:78) ~[na:1.8.0_151]
  at java.io.InputStreamReader.<init>(InputStreamReader.java:72) ~[na:1.8.0_151]
  at com.facebook.ads.sdk.APIRequest.readResponse(APIRequest.java:218) ~[facebook-java-ads-sdk-2.11.1.jar!/:na]
  at com.facebook.ads.sdk.APIRequest.access$100(APIRequest.java:47) ~[facebook-java-ads-sdk-2.11.1.jar!/:na]
  at com.facebook.ads.sdk.APIRequest$DefaultRequestExecutor.sendDelete(APIRequest.java:426) ~[facebook-java-ads-sdk-2.11.1.jar!/:na]
  at com.facebook.ads.sdk.APIRequest$DefaultRequestExecutor.execute(APIRequest.java:336) ~[facebook-java-ads-sdk-2.11.1.jar!/:na]
  at com.facebook.ads.sdk.APIRequest.executeInternal(APIRequest.java:160) ~[facebook-java-ads-sdk-2.11.1.jar!/:na]
  at com.facebook.ads.sdk.CustomAudience$APIRequestDeleteUsers.execute(CustomAudience.java:1732) ~[facebook-java-ads-sdk-2.11.1.jar!/:na]
  at com.facebook.ads.sdk.CustomAudience$APIRequestDeleteUsers.execute(CustomAudience.java:1727) ~[facebook-java-ads-sdk-2.11.1.jar!/:na]
```

Line: https://github.com/facebook/facebook-java-ads-sdk/blob/5e971724ce185db15721d116247a7bae7f20f23a/src/main/java/com/facebook/ads/sdk/APIRequest.java#L218

Version: 2.11.1

**Comment by guillermo-12gigs** [comment]
I'm experiencing the same issue. Any comments?

**Comment by kevinwenzhang** [comment]
Same issue. This is preventing the actual `APIException` from being thrown, which we would want. Are there any updates to this? I've been over a year now.
