### ISSUE TITLE
The JsonDeserializer EnumTypeAdapter failed to deserialized json object "MULTI_HASHES"

### ISSUE THREAD

**Issue by varadark** [facebook/facebook-java-business-sdk#144]
While trying to retrieve a custom audience using the Facebook Java SDK (v 2.11.1) I get the following error and stack trace.

    try {
          CustomAudience audience = CustomAudience.fetchById(audienceID, context);
    } catch (APIException ex) {
          ex.printStackTrace();
    }

```
com.facebook.ads.sdk.APIException$MalformedResponseException: Invalid response string: {"account_id":"...","approximate_count":-1,"data_source":{"type":"FILE_IMPORTED","sub_type":"MULTI_HASHES","creation_params":"[]"},"delivery_status":{"code":200,"description":"This audience is ready for use."},"description":"...","id":"...","is_value_based":false,"name":"...","operation_status":{"code":200,"description":"Normal"},"permission_for_actions":{"can_edit":true,"can_see_insight":true,"can_share":true,"subtype_supports_lookalike":true,"supports_recipient_lookalike":false},"retention_days":0,"subtype":"CUSTOM","time_content_updated":1522174897,"time_created":1522174896,"time_updated":1522174897}
	at com.facebook.ads.sdk.CustomAudience.parseResponse(CustomAudience.java:257)
	at com.facebook.ads.sdk.CustomAudience$APIRequestGet.parseResponse(CustomAudience.java:2045)
	at com.facebook.ads.sdk.CustomAudience$APIRequestGet.execute(CustomAudience.java:2055)
	at com.facebook.ads.sdk.CustomAudience$APIRequestGet.execute(CustomAudience.java:2050)
	at com.facebook.ads.sdk.CustomAudience.fetchById(CustomAudience.java:126)
....
Caused by: com.google.gson.JsonParseException: The JsonDeserializer EnumTypeAdapter failed to deserialized json object "MULTI_HASHES" given the type class com.facebook.ads.sdk.CustomAudienceDataSource$EnumSubType
	at com.google.gson.JsonDeserializerExceptionWrapper.deserialize(JsonDeserializerExceptionWrapper.java:63)
	at com.google.gson.JsonDeserializationVisitor.invokeCustomDeserializer(JsonDeserializationVisitor.java:88)
	at com.google.gson.JsonObjectDeserializationVisitor.visitFieldUsingCustomHandler(JsonObjectDeserializationVisitor.java:116)
	at com.google.gson.ObjectNavigator.navigateClassFields(ObjectNavigator.java:158)
	at com.google.gson.ObjectNavigator.accept(ObjectNavigator.java:131)
	at com.google.gson.JsonDeserializationVisitor.visitChild(JsonDeserializationVisitor.java:107)
	at com.google.gson.JsonDeserializationVisitor.visitChildAsObject(JsonDeserializationVisitor.java:95)
	at com.google.gson.JsonObjectDeserializationVisitor.visitObjectField(JsonObjectDeserializationVisitor.java:61)
	at com.google.gson.ObjectNavigator.navigateClassFields(ObjectNavigator.java:164)
	at com.google.gson.ObjectNavigator.accept(ObjectNavigator.java:131)
	at com.google.gson.JsonDeserializationContextDefault.fromJsonObject(JsonDeserializationContextDefault.java:73)
	at com.google.gson.JsonDeserializationContextDefault.deserialize(JsonDeserializationContextDefault.java:51)
	at com.google.gson.Gson.fromJson(Gson.java:568)
	at com.google.gson.Gson.fromJson(Gson.java:515)
	at com.google.gson.Gson.fromJson(Gson.java:484)
	at com.google.gson.Gson.fromJson(Gson.java:434)
	at com.google.gson.Gson.fromJson(Gson.java:406)
	at com.facebook.ads.sdk.CustomAudience.loadJSON(CustomAudience.java:147)
	at com.facebook.ads.sdk.CustomAudience.parseResponse(CustomAudience.java:250)
	... 12 more
Caused by: java.lang.IllegalArgumentException: No enum constant com.facebook.ads.sdk.CustomAudienceDataSource.EnumSubType.MULTI_HASHES
	at java.lang.Enum.valueOf(Enum.java:238)
	at com.google.gson.DefaultTypeAdapters$EnumTypeAdapter.deserialize(DefaultTypeAdapters.java:410)
	at com.google.gson.DefaultTypeAdapters$EnumTypeAdapter.deserialize(DefaultTypeAdapters.java:400)
	at com.google.gson.JsonDeserializerExceptionWrapper.deserialize(JsonDeserializerExceptionWrapper.java:50)
```
I am using the gson-2.5 package. I also tested with the latest gson-2.8.2. The error is reproducible with that as well. Can you please help?

**Comment by codytwinton** [comment]
It seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.
