### ISSUE TITLE
NullPointerException when using Auto-pagination 

### ISSUE THREAD

**Issue by salunkeganesh93** [facebook/facebook-java-business-sdk#212]
I am using auto-pagination for fetching campaigns for adAccount as below
```
AdAccount adAccount = new AdAccount("actual_account_id", context);
APINodeList<Campaign> campaigns = adAccount.getCampaigns().execute().withAutoPaginationIterator(true);
```
NullPointerException on following line
```
campaigns.stream().map(Campaign::getFieldName).collect(Collectors.toList());
```
This happens when there are no campaigns in this account. Even if there is one campaign this works fine.

Stacktrace 
`Exception in thread "main" java.lang.NullPointerException
	at com.facebook.ads.sdk.APINodeList$APINodeListAutoPaginationSpliterator.tryAdvance(APINodeList.java:217)
	at java.util.Spliterator.forEachRemaining(Spliterator.java:326)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at net.dds.integration.resource.impl.FacebookCampaignResourceImpl.main(FacebookCampaignResourceImpl.java:120)`

**Comment by jingping2015** [comment]
Hi, Thanks for reporting this issue, it should be fixed in our new release.
