### ISSUE TITLE
Failed to create ad with "Unsupported post request" error

### ISSUE THREAD

**Issue by gnillor** [facebook/facebook-java-business-sdk#229]
### Which SDK version are you using?
3.2.9

### What's the issue?
Create creative, campaign, ad set successfully, but when exception thown when creating ad
```
Caused by: com.facebook.ads.sdk.APIException$FailedRequestException: {"error":{"message":"Unsupported post request.","type":"GraphMethodException","code":100,"fbtrace_id":"EdleheOfV1E"}}
	at com.facebook.ads.sdk.APIRequest.readResponse(APIRequest.java:306)
	at com.facebook.ads.sdk.APIRequest.access$100(APIRequest.java:53)
	at com.facebook.ads.sdk.APIRequest$DefaultRequestExecutor.sendPost(APIRequest.java:579)
	at com.facebook.ads.sdk.APIRequest$DefaultRequestExecutor.execute(APIRequest.java:511)
	at com.facebook.ads.sdk.APIRequest.executeInternal(APIRequest.java:198)
	at com.facebook.ads.sdk.AdAccount$APIRequestCreateAd.execute(AdAccount.java:7274)
	at com.facebook.ads.sdk.AdAccount$APIRequestCreateAd.execute(AdAccount.java:7269)
	at com.alipay.iadvertise.core.service.external.client.facebook.FbAdClient.createAd(FbAdClient.java:57)
```

### Steps/Sample code to reproduce the issue
1. create dynamic creative (app install)
2. create campaign (app install)
3. create ad set (app install, register app event)
4. create ad

#### Observed Results:

  * What happened?  This could be a description, log output, etc.
Unsupported post request

#### Expected Results:

  * What did you expect to happen?
Wish ad created

**Comment by gnillor** [comment]
Now, this issue is fixed, closed.
