### ISSUE TITLE
NullPointerException while reading the response

### ISSUE THREAD

**Issue by sathieshlokanadan** [facebook/facebook-java-business-sdk#295]
Hello team,

We are getting the following exception occasionally. Could you please let us know the reason and how to avoid these errors? We are using Facebook Business SDK v6.0.0.

Caused by: java.lang.NullPointerException
at java.io.Reader.&lt;init&gt;(Reader.java:78)
at java.io.InputStreamReader.&lt;init&gt;(InputStreamReader.java:72)
at com.facebook.ads.sdk.APIRequest.readResponse(APIRequest.java:298)
at com.facebook.ads.sdk.APIRequest.access$100(APIRequest.java:53)
at com.facebook.ads.sdk.APIRequest$DefaultRequestExecutor.sendGet(APIRequest.java:533)
at com.facebook.ads.sdk.APIRequest$DefaultRequestExecutor.execute(APIRequest.java:517)
at com.facebook.ads.sdk.APIRequest.executeInternal(APIRequest.java:198)
at com.facebook.ads.sdk.AdAccount$APIRequestGetCustomAudiences.execute(AdAccount.java:16189)
at com.facebook.ads.sdk.AdAccount$APIRequestGetCustomAudiences.execute(AdAccount.java:16184)
at com.facebook.ads.sdk.AdAccount$APIRequestGetCustomAudiences.execute(AdAccount.java:16160)

**Comment by przemek-baranowski** [comment]
Did you tried to use newer version of SDK? ie. 6.0.4? Maybe it is fixed...

**Comment by lxhj** [comment]
same issues!~
