### ISSUE TITLE
Marketing API Java SDK v5.0 APIRequestGetCampaigns blocks forever for ad account id 1524460767670812

### ISSUE THREAD

**Issue by hackathon-dtu** [facebook/facebook-java-business-sdk#299]
### Which SDK version are you using?
<dependency>
      <groupId>com.facebook.business.sdk</groupId>
      <artifactId>facebook-java-business-sdk</artifactId>
      <version>5.0.6</version>
</dependency>

### What's the issue?
The socket call blocks indefinitely because the API endpoint didn't respond. We only have this issue for this particular ad account. We expect the call to return a response eventually.

### Steps/Sample code to reproduce the issue
This is not reliably reproduce-able. It happens once in a while.
``
accessToken = SYSTEM_USER_ACCESS_TOKEN_FOR_BUSINESS_ID_1742903229317470;
APIContext context = new APIContext(accessToken,null,null,false);
APINodeList<Campaign> campaigns = new AdAccount("1524460767670812", context)
        .getCampaigns()
        .requestIdField()
        .execute();
``

#### Observed Results:

  * What happened?  This could be a description, log output, etc.
thread dump

java.lang.Thread.State: RUNNABLE
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.read(InputRecord.java:503)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:983)
	- locked <0x00000005c26cb5b8> (a java.lang.Object)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1385)
	- locked <0x00000005c26cb628> (a java.lang.Object)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
	- locked <0x00000005c26cb638> (a sun.net.www.protocol.https.DelegateHttpsURLConnection)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	- locked <0x00000005c26cb638> (a sun.net.www.protocol.https.DelegateHttpsURLConnection)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:347)
	at com.facebook.ads.sdk.APIRequest.readResponse(APIRequest.java:285)
	at com.facebook.ads.sdk.APIRequest.access$100(APIRequest.java:53)
	at com.facebook.ads.sdk.APIRequest$DefaultRequestExecutor.sendGet(APIRequest.java:533)
	at com.facebook.ads.sdk.APIRequest$DefaultRequestExecutor.execute(APIRequest.java:517)
	at com.facebook.ads.sdk.APIRequest.executeInternal(APIRequest.java:198)
	at com.facebook.ads.sdk.AdAccount$APIRequestGetCampaigns.execute(AdAccount.java:16143)
	at com.facebook.ads.sdk.AdAccount$APIRequestGetCampaigns.execute(AdAccount.java:16138)

#### Expected Results:

  * What did you expect to happen?
The call returns with the list of AdCampaign objects.

**Comment by sweekyforzymail** [comment]
Trying to update SDK version to 7 ?
