### ISSUE TITLE
Reader java.lang.NullPointerException

### ISSUE THREAD

**Issue by lxhj** [facebook/facebook-java-business-sdk#350]
### new AdAccountActivity(app_id, context).get()
                    .execute();

#### Observed Results:

  ========Start of API Call========
Request:
GET: https://graph.facebook.com/v11.0/318195943378741/?access_token=EAAEhZAcQsjzUBAFZBwe........................

#### Expected Results:

  ========Start of API Call========
Request:
GET: https://graph.facebook.com/v11.0/318195943378741/?access_token=EAAEhZAcQsjzUBAFZBweJIt2ZAH3tDuh90Hu0ZCVBqjmIry7Lxt0BnZCYSOI1VTguvmkYWjCt1ZBUAXhKPkU4GNuLd9wF7CBhsDLuKFvf1ZCZCSiZCEiKkAg4FnEzqGWzZBkG8j3J5X9rAAXIwLUOFSDZC6D1K96gkDrPeVTAxZAUsiooo8DgaBh8mXurp0tFLHIdvIgZD&appsecret_proof=a7ad63b332d056e934126f233ae6e644197430f5a9ef4e88bf06b108ea1a4fd3
Exception in thread "main" java.lang.NullPointerException
	at java.io.Reader.<init>(Reader.java:78)
	at java.io.InputStreamReader.<init>(InputStreamReader.java:72)
	at com.facebook.ads.sdk.APIRequest.readResponse(APIRequest.java:300)
	at com.facebook.ads.sdk.APIRequest.access$100(APIRequest.java:52)
	at com.facebook.ads.sdk.APIRequest$DefaultRequestExecutor.sendGet(APIRequest.java:535)
	at com.facebook.ads.sdk.APIRequest$DefaultRequestExecutor.execute(APIRequest.java:519)
	at com.facebook.ads.sdk.APIRequest.executeInternal(APIRequest.java:197)
	at com.facebook.ads.sdk.AdAccountActivity$APIRequestGet.execute(AdAccountActivity.java:511)
	at com.facebook.ads.sdk.AdAccountActivity$APIRequestGet.execute(AdAccountActivity.java:506)
	at com.facebook.ads.MainApplication.main(MainApplication.java:16)

**Comment by lxhj** [comment]
network issues, closed
