### ISSUE TITLE
Unrecognized appID, cannot enable CrashReporter!

### ISSUE THREAD

**Issue by empireisme** [facebook/facebook-java-business-sdk#412]
### Which SDK version are you using?
16.0
### What's the issue?
When i do the QuickStart example,i get Unrecognized appID, cannot enable CrashReporter! in my console.
I am pretty sure my access token and app secret is good because i can get data from fb server by browser

something like:

https://graph.facebook.com/v14.0/act_XXXXXXXXXXXX/insights?
access_token=MYACESSTOKEN
&level=adset
&time_range={"since":"2022-01-01","until":"2022-01-31"}
&breakdowns=country
&sort=clicks
&fields=reach,impressions,spend,cpm,actions
&filtering=[{"field":"clicks","operator":"GREATER_THAN","value":"5000"}]

### Steps/Sample code to reproduce the issue
```
public class QuickStartExample {

	  public static final String ACCESS_TOKEN = FbApi.TOKEN;
	  public static final Long ACCOUNT_ID = XXXXXXXXXXXXXXXXL;
	  public static final String APP_SECRET = FbApi.APP_SERECT;

//	  public static final APIContext context = new APIContext(ACCESS_TOKEN, APP_SECRET);
	  public static void main(String[] args) throws APIException {
		  APIContext context = new APIContext(ACCESS_TOKEN, APP_SECRET);
	      AdAccount account = new AdAccount(ACCOUNT_ID, context);
	      Campaign campaign = account.createCampaign()
	    	        .setName("Java SDK Test Campaign")
	    	        .setObjective(Campaign.EnumObjective.VALUE_LINK_CLICKS)
	    	        .setSpendCap(10000L)
	    	        .setStatus(Campaign.EnumStatus.VALUE_PAUSED)
	    	        .execute();
	    	      System.out.println(campaign.fetch());
	  }
}
```
#### Observed Results:

```
CrashReporter : Unrecognized appID, cannot enable CrashReporter!
Exception in thread "main" com.facebook.ads.sdk.APIException$FailedRequestException: java.net.SocketException: Connection reset
	at com.facebook.ads.sdk.APIRequest.executeInternal(APIRequest.java:203)
	at com.facebook.ads.sdk.AdAccount$APIRequestCreateCampaign.execute(AdAccount.java:14964)
	at com.facebook.ads.sdk.AdAccount$APIRequestCreateCampaign.execute(AdAccount.java:14959)
	at com.taiwanmobile.madp.portal.service.meta.QuickStartExample.main(QuickStartExample.java:24)
Caused by: java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:210)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.read(InputRecord.java:503)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:983)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1385)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1316)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1291)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:250)
	at com.facebook.ads.sdk.APIRequest$DefaultRequestExecutor.sendPost(APIRequest.java:556)
	at com.facebook.ads.sdk.APIRequest$DefaultRequestExecutor.execute(APIRequest.java:523)
	at com.facebook.ads.sdk.APIRequest.executeInternal(APIRequest.java:198)
	... 3 more
```

#### Expected Results:

 can get the good object of

`APIContext context = new APIContext(ACCESS_TOKEN, APP_SECRET);`

by the way my access token is permanent

**Comment by empireisme** [comment]
sorry，my secret is wrong,but i have another problem
